let
    Source = fxCsv("data/raw/incidents_raw.csv"),
    Selected = Table.SelectColumns(Source, {"incident_id", "alert_id", "created_at", "acknowledged_at", "triaged_at", "contained_at", "resolved_at", "closed_at", "source_product", "source_system", "asset_id", "rule_id", "severity", "status", "analyst_id", "classification_key", "risk_score", "is_escalated", "is_reopened", "data_classification"}),
    NormalizeLabels = Table.TransformColumns(Selected, {{"severity", fxNormalizeSeverity, type text}, {"status", fxNormalizeStatus, type text}, {"analyst_id", each if _ = null or Text.Trim(_) = "" then "UNKNOWN" else Text.Trim(_), type text}}),
    Typed = Table.TransformColumnTypes(NormalizeLabels, {{"created_at", type datetimezone}, {"acknowledged_at", type datetimezone}, {"triaged_at", type datetimezone}, {"contained_at", type datetimezone}, {"resolved_at", type datetimezone}, {"closed_at", type datetimezone}, {"classification_key", Int64.Type}, {"risk_score", type number}, {"is_escalated", type logical}, {"is_reopened", type logical}}),
    Deduplicated = Table.Distinct(Table.SelectRows(Typed, each [incident_id] <> null and [created_at] <> null and [severity] <> null and [status] <> null), {"incident_id"}),
    WithIncidentKey = Table.AddColumn(Deduplicated, "IncidentKey", each Number.FromText(Text.AfterDelimiter([incident_id], "-")), Int64.Type),
    AlertLookup = Table.AddColumn(Table.Distinct(Table.SelectColumns(fxCsv("data/raw/alerts_raw.csv"), {"alert_id"})), "AlertKey", each Number.FromText(Text.AfterDelimiter([alert_id], "-")), Int64.Type),
    MergeAlert = Table.NestedJoin(WithIncidentKey, {"alert_id"}, AlertLookup, {"alert_id"}, "Alert", JoinKind.LeftOuter),
    ExpandAlert = Table.ExpandTableColumn(MergeAlert, "Alert", {"AlertKey"}, {"AlertKey"}),
    MergeSource = Table.NestedJoin(ExpandAlert, {"source_product", "source_system"}, DimSourceProduct, {"SourceProduct", "SourceSystem"}, "Source", JoinKind.LeftOuter),
    ExpandSource = Table.ExpandTableColumn(MergeSource, "Source", {"SourceProductKey"}, {"SourceProductKey"}),
    MergeAsset = Table.NestedJoin(ExpandSource, {"asset_id"}, DimAsset, {"AssetId"}, "Asset", JoinKind.LeftOuter),
    ExpandAsset = Table.ExpandTableColumn(MergeAsset, "Asset", {"AssetKey"}, {"AssetKey"}),
    MergeRule = Table.NestedJoin(ExpandAsset, {"rule_id"}, DimDetectionRule, {"RuleId"}, "Rule", JoinKind.LeftOuter),
    ExpandRule = Table.ExpandTableColumn(MergeRule, "Rule", {"DetectionRuleKey"}, {"DetectionRuleKey"}),
    MergeSeverity = Table.NestedJoin(ExpandRule, {"severity"}, DimSeverity, {"Severity"}, "SeverityDim", JoinKind.LeftOuter),
    ExpandSeverity = Table.ExpandTableColumn(MergeSeverity, "SeverityDim", {"SeverityKey"}, {"SeverityKey"}),
    MergeStatus = Table.NestedJoin(ExpandSeverity, {"status"}, DimStatus, {"Status"}, "StatusDim", JoinKind.LeftOuter),
    ExpandStatus = Table.ExpandTableColumn(MergeStatus, "StatusDim", {"StatusKey"}, {"StatusKey"}),
    MergeAnalyst = Table.NestedJoin(ExpandStatus, {"analyst_id"}, DimAnalyst, {"AnalystId"}, "Analyst", JoinKind.LeftOuter),
    ExpandAnalyst = Table.ExpandTableColumn(MergeAnalyst, "Analyst", {"AnalystKey"}, {"AnalystKey"}),
    AddDateKey = Table.AddColumn(ExpandAnalyst, "CreatedDateKey", each Number.FromText(Date.ToText(Date.From([created_at]), "yyyyMMdd")), Int64.Type),
    AddTimeKey = Table.AddColumn(AddDateKey, "CreatedTimeKey", each Time.Hour(Time.From([created_at])) * 100 + Number.IntegerDivide(Time.Minute(Time.From([created_at])), 5) * 5, Int64.Type),
    AddAck = Table.AddColumn(AddTimeKey, "AcknowledgementMinutes", each if [acknowledged_at] = null then null else Duration.TotalMinutes([acknowledged_at]-[created_at]), type number),
    AddTriage = Table.AddColumn(AddAck, "TriageMinutes", each if [triaged_at] = null then null else Duration.TotalMinutes([triaged_at]-[created_at]), type number),
    AddContain = Table.AddColumn(AddTriage, "ContainmentMinutes", each if [contained_at] = null then null else Duration.TotalMinutes([contained_at]-[created_at]), type number),
    AddResolve = Table.AddColumn(AddContain, "ResolutionMinutes", each if [resolved_at] = null then null else Duration.TotalMinutes([resolved_at]-[created_at]), type number),
    AddRecovery = Table.AddColumn(AddResolve, "RecoveryMinutes", each if [closed_at] = null or [resolved_at] = null then null else Duration.TotalMinutes([closed_at]-[resolved_at]), type number),
    AddCount = Table.AddColumn(AddRecovery, "IncidentCount", each 1, Int64.Type),
    AddSLAKey = Table.AddColumn(AddCount, "SLAKey", each [SeverityKey], Int64.Type),
    MergeSLA = Table.NestedJoin(AddSLAKey, {"SLAKey"}, DimSLA, {"SLAKey"}, "SLADim", JoinKind.LeftOuter),
    ExpandSLA = Table.ExpandTableColumn(MergeSLA, "SLADim", {"AcknowledgeMinutes", "ContainMinutes", "ResolveMinutes"}, {"AcknowledgeTarget", "ContainTarget", "ResolveTarget"}),
    AddSLAOverall = Table.AddColumn(ExpandSLA, "SLAOverallMet", each [AcknowledgementMinutes] <> null and [ContainmentMinutes] <> null and [ResolutionMinutes] <> null and [AcknowledgementMinutes] <= [AcknowledgeTarget] and [ContainmentMinutes] <= [ContainTarget] and [ResolutionMinutes] <= [ResolveTarget], type logical),
    AddFalsePositive = Table.AddColumn(AddSLAOverall, "IsFalsePositive", each List.Contains({2, 3}, [classification_key]), type logical),
    Renamed = Table.RenameColumns(AddFalsePositive, {{"incident_id", "IncidentId"}, {"created_at", "CreatedAtUTC"}, {"acknowledged_at", "AcknowledgedAtUTC"}, {"triaged_at", "TriagedAtUTC"}, {"contained_at", "ContainedAtUTC"}, {"resolved_at", "ResolvedAtUTC"}, {"closed_at", "ClosedAtUTC"}, {"classification_key", "ClassificationKey"}, {"risk_score", "RiskScore"}, {"is_escalated", "IsEscalated"}, {"is_reopened", "IsReopened"}, {"data_classification", "DataClassification"}}),
    Final = Table.SelectColumns(Renamed, {"IncidentKey", "IncidentId", "CreatedAtUTC", "AcknowledgedAtUTC", "TriagedAtUTC", "ContainedAtUTC", "ResolvedAtUTC", "ClosedAtUTC", "CreatedDateKey", "CreatedTimeKey", "SourceProductKey", "AssetKey", "DetectionRuleKey", "SeverityKey", "StatusKey", "AnalystKey", "ClassificationKey", "SLAKey", "AlertKey", "IncidentCount", "RiskScore", "AcknowledgementMinutes", "TriageMinutes", "ContainmentMinutes", "ResolutionMinutes", "RecoveryMinutes", "IsEscalated", "IsReopened", "IsFalsePositive", "SLAOverallMet", "DataClassification"})
in
    Final
